### ISSUE TITLE
Formula 1

### ISSUE THREAD

**Issue by DanielZolfaghari** [anyproto/gallery#125]
### Experience

[Formula1.zip](https://github.com/user-attachments/files/15926455/Formula1.zip)

### Title

Formula 1

### Screenshots

![image](https://github.com/anyproto/gallery/assets/98016712/abc54393-3cda-4538-9927-4ba9d07efc7a)
![image](https://github.com/anyproto/gallery/assets/98016712/3a4b33e7-a12b-4a67-a14c-c9e548c0f765)
![image](https://github.com/anyproto/gallery/assets/98016712/c19e36b4-2732-4ff6-a044-33eaafd4ffff)
![image](https://github.com/anyproto/gallery/assets/98016712/596e48f5-a50c-4c28-a9e5-a81eb5b0e702)

### Description

Experience Formula 1 like never before!

### Categories

Hobbies

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by KirillSto** [comment]
Hello, @DanielZolfaghari! Thank you for your contribution! The experience is really interesting and outstanding!

However I have noticed some objects that seem to be redundant in the archive. Please correct me if I am wrong!
These are:
- collection **'Protobuf Import 2024-06-20T09:17:31+03:30'** that was most possibly generated on import of some archive
- and 5 templates **Actor**, **Director**, **Author**, **Composer** and **Faculty** that include inline sets linked to some objects not presented in the archive. It seems that these templates do not correlate with F1

If you agree with me, you can delete these objects by yourself or allow me to do it from our side. Collection is accessible via graph or search, while templates are accessible via the page of **Human** object type.

Moreover, please consider that object **'Alpine A523'** misses values of details '**Constructed by**' and **'Driven by'**. This is either a bug on side of Anytype export, or the objects related to these people were deleted from space. You can either restore these objects and links from Alpine, or we can remain them empty. It is up to you :slightly_smiling_face:

**Comment by DanielZolfaghari** [comment]
Hello Kirill, 

My Pleasure 😊 and I appreciate your feedback. 


You are right. I forgot to delete the collection and also my other templates for object type human. They will be used in my other submission in the future 😉. 

As for the A523, yeah. You can fill the "driven by" with "Esteban Ocon" which is already among the objects. As of the constructor, I think I haven't made one for Alpine yet. So, I think it's ok to leave it empty. 

My goal was to show people what is possible mainly through Max, Monaco Grand Prix, the Monaco circuit and Red bull. 

Feel free to make changes on your end.

**Comment by KirillSto** [comment]
Thank you for explanation, @DanielZolfaghari !
I have applied changes and re-uploaded the archive. I guess it will pass validation this time :slightly_smiling_face: 

We are looking forward to see your future experiences :wink:
