### ISSUE TITLE
The Ultimate Anti-Aging Workout by Bryan Johnson

### ISSUE THREAD

**Issue by Balcion** [anyproto/gallery#128]
### Experience

[Anytype.20240710.190755.63.zip](https://github.com/user-attachments/files/16166583/Anytype.20240710.190755.63.zip)

### Title

Anti-Aging Workout by Bryan Johnson

### Screenshots

![COVER](https://github.com/anyproto/gallery/assets/175219548/d97ff866-b09b-4b61-b4e7-2a377c2eca14)

### Description

Please note that all content is the original work of Bryan Johnson! Everything Bryan does is free and shareable! I've edited and structured the parts for convenience.

HD files-> https://drive.google.com/file/d/1Af4WFHazjYaK02nye8soLQ-cHhrf-Dy

### Categories

Health & Fitness

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by Balcion** [comment]
Hey @fuksman thanks for approving! How long does it take to show up in the gallery? I cant see it. Best Regards

**Comment by Balcion** [comment]
Link gives an error: anytype://main/import/?type=experience&source=https%3A%2F%2Fgithub.com%2Fanyproto%2Fgallery%2Fraw%2Fanti_aging_workout_by_bryan_johnson%2Fexperiences%2Fanti_aging_workout_by_bryan_johnson%2Ftest-manifest.json

**Comment by fuksman** [comment]
Hello @Balcion, the experience is published.

**Comment by Balcion** [comment]
I added a second preview picture and updated the HD files link.

**Comment by Balcion** [comment]
I made sure the HD files link is working

**Comment by fuksman** [comment]
Hello @Balcion, can you please submit a new version of the experience by creating a new issue, instead of editing the previous one? Just check that the experience title is the same. 
Thank you!

**Comment by Balcion** [comment]
Hello @fuksman resubmitting the entire experience just to edit the description seems a bit unnecessary. Is there a way to avoid this?
