### ISSUE TITLE
New Experience : A Student Need

### ISSUE THREAD

**Issue by DaytonID** [anyproto/gallery#146]
### Experience

[A Student Need.zip](https://github.com/user-attachments/files/17266549/A.Student.Need.zip)

### Title

A Student Need

### Screenshots

![Screenshot1](https://github.com/user-attachments/assets/cd03cf13-7ae3-4a99-a01b-dd661273664b)
![Screenshot2](https://github.com/user-attachments/assets/f4b1aaf4-7310-4bd6-a9a0-78c817d2b4c5)
![Screenshot3](https://github.com/user-attachments/assets/a735ab27-ab9b-410e-835a-30399293ddfa)
![Screenshot4](https://github.com/user-attachments/assets/0aed7d0d-408b-4d6a-a57f-1cd2fdb797b8)
![Screenshot5](https://github.com/user-attachments/assets/31185a07-3b15-4c55-b009-51aed6dc45e7)

### Description

Students can use this template to plan homework tasks and exam arrangements for each semester.

### Categories

Education, Personal Growth, Other

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by RomanSelischev** [comment]
Solution log has unsupported format on the current version of Anytype

**Comment by DaytonID** [comment]
> Solution log has unsupported format on the current version of Anytype
@RomanSelischev Did you download it from the software gallery?
