### ISSUE TITLE
YAPKMS - Yet Another PKM Space

### ISSUE THREAD

**Issue by telmob** [anyproto/gallery#148]
### Experience

[ YAPKMS.zip](https://github.com/user-attachments/files/17820009/YAPKMS.zip)

### Title

YAPKMS - Yet Another PKM Space

### Screenshots

![Screenshot1](https://github.com/user-attachments/assets/d5b5ca97-76a3-4cc0-bca3-7312741587ae)
![Screenshot2](https://github.com/user-attachments/assets/8ef9e419-881d-4fe8-9224-b1aa1ca9ec83)
![Screenshot3](https://github.com/user-attachments/assets/5af334aa-abb2-414b-af9f-05c1fc86c145)
![Screenshot4](https://github.com/user-attachments/assets/fc3243bc-5e0e-489c-b435-4fca1dc30899)
![Screenshot5](https://github.com/user-attachments/assets/8f015353-c7c9-4277-bc87-15893c2cf5a9)
![Screenshot6](https://github.com/user-attachments/assets/804aa70b-43db-4151-a431-3a14beca2d26)
![Screenshot7](https://github.com/user-attachments/assets/be11df88-99f1-4386-afe7-300c58a82478)
![Screenshot8](https://github.com/user-attachments/assets/bac5d9f2-6a31-4f24-949a-c0973c572544)

### Description

YAPKMS is an adaptation of the Second Brain's concept so that it can be used daily.
It's meant to be easy to use, yet, as organized as you want it to be. Remember, there's no 'one size fits all'. You are encoraged to customize this space the way you want to.

### Categories

Dashboard, Work, Education, Project tracking, Health & Fitness, Finance, Food & Nutrition, Travel, Hobbies, Home

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by telmob** [comment]
Well, that was overwhelming... Do i actually need to do something? I see alot of info that shouldn't be in there. Some deleted stuff appears there. Weird.

**Comment by KirillSto** [comment]
> Well, that was overwhelming... Do i actually need to do something? I see alot of info that shouldn't be in there. Some deleted stuff appears there. Weird.

Thank you for uploading your experience! Let us take a look into the issues found by validator. If we need your assistance, we'll ask you to re-export space one more time

**Comment by telmob** [comment]
> > Well, that was overwhelming... Do i actually need to do something? I see alot of info that shouldn't be in there. Some deleted stuff appears there. Weird.
> 
> Thank you for uploading your experience! Let us take a look into the issues found by validator. If we need your assistance, we'll ask you to re-export space one more time

Thank you. I need to make a change to my 'experience', but i need to wait for the issue with deleted objects to be resolved.

**Comment by telmob** [comment]
Is it possible for me to update the current file still?
I made some important changes.
Oh, and btw, will it possible to keep my file updated after submiting?

**Comment by KirillSto** [comment]
@telmob sorry for really prolonged reply. The problem was connected with relation options (tag-like objects) that remained in space despite the very relation was deleted. This bug is already fixed, so I have cleaned your archive from these objects

**Comment by telmob** [comment]
> @telmob sorry for really prolonged reply. The problem was connected with relation options (tag-like objects) that remained in space despite the very relation was deleted. This bug is already fixed, so I have cleaned your archive from these objects

No worries. Thank you :)

**Comment by telmob** [comment]
> /gallery approve

Not wishing to be picky, but would it be possible to have the first image as cover for the Space in Gallery? It's looking weird.

**Comment by telmob** [comment]
> YAP KMS is a crazy title 
I lack imagination. Sorry about that
