### ISSUE TITLE
Meeting Notes Management

### ISSUE THREAD

**Issue by ChristianHaake** [anyproto/gallery#19]
### Experience

[Anytype-Meetingnotes Setup.zip](https://github.com/anyproto/gallery/files/13757308/Anytype-Meetingnotes.Setup.zip)

### Title

Meeting Notes Management

### Screenshots
![2023_Antype-Meetingsnotes](https://github.com/anyproto/gallery/assets/48489823/ccf0073f-898e-44d2-a08d-207b514d23c1)
![2023_Anytype-Note Template](https://github.com/anyproto/gallery/assets/48489823/82c358fb-7605-4313-a382-b01d9a682c9f)

### Description

Anytype is characterized by its high flexibility, allowing users to structure the tool according to their specific needs. This led to the creation of a new object called “Meeting Note”, under which each new meeting note is recorded. To ensure consistency, the same template is always used for meeting notes. This simplifies the process and ensures uniform additional information for each entry.

The meeting notes are collected in a set called “Meeting Notes”. This set acts as a database where all meeting notes are organized. The Table-View is preferred, as it provides a clear overview of all entries and contains fixed columns for relations or additional information required for specific workflows You may check my article for a full explanation: https://haak3.de/articles/2023_Anytype/2023_Anytype-Meetingnotes/2023_Antype-Meetingnotes-EN.html

### Categories

Work

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by fuksman** [comment]
Hello @ChristianHaake, thank you for your contribution! Can you please remove "with Anytype" from the title of the experience?

**Comment by ChristianHaake** [comment]
@fuksman done :-)

**Comment by fuksman** [comment]
I meant inside the issue, under the "Title" field :)

**Comment by ChristianHaake** [comment]
ahh. done. thanks!

Merry Christmas :-)

**Comment by fuksman** [comment]
@ChristianHaake, the attached archive is unexpectedly large. Please check if there are any unnecessary files inside, as well as unused or archived objects.

**Comment by ChristianHaake** [comment]
![CleanShot 2023-12-23 at 17 03 50@2x](https://github.com/anyproto/gallery/assets/48489823/8b3ffdea-5952-4590-8713-f3c0d571a858)

Kinda wierd.. there where only 2-3 other set objects in there... now none.. and still not really smaller. 
[Anytype-Meetingnotes Setup.zip](https://github.com/anyproto/gallery/files/13760342/Anytype-Meetingnotes.Setup.zip)
