### ISSUE TITLE
Application of PARA and CODER (Full setup)

### ISSUE THREAD

**Issue by ChristianHaake** [anyproto/gallery#22]
### Experience

[Anytype-PARA.zip](https://github.com/anyproto/gallery/files/13760365/Anytype-PARA.zip)

### Title

PARA and CODER Setup

### Screenshots

![2023-10-14_Anytype-PARA-Project](https://github.com/anyproto/gallery/assets/48489823/652ae224-7997-4304-9248-47b9f658d7aa)

![2023-10-14_Anytype-PARA-Page](https://github.com/anyproto/gallery/assets/48489823/de4a265f-2e50-4ef0-8d2b-366915b521e2)

![2023-10-14_Anytype-PARA-Page-setfilter](https://github.com/anyproto/gallery/assets/48489823/9cbc8e66-e47d-4ebd-a25d-c13ee66742d6)
![2023-10-14_Anytype-PARA-AREAS](https://github.com/anyproto/gallery/assets/48489823/12fcf50b-e6ee-4c82-b770-acd02d22d147)

![2023-10-14_Anytype-PARA-Wiki-overview](https://github.com/anyproto/gallery/assets/48489823/6046dbbf-d8cd-4536-9699-cb95613ba9f4)

![2023-10-14_Anytype-PARA-Wiki-Gallery](https://github.com/anyproto/gallery/assets/48489823/f7c34f5a-9724-416d-bdec-1b07c8030c48)

### Description

Anytype, as an advanced note-taking app, not only combines the robust data management features of Notion but also integrates the “on-device” premise of Obsidian, allowing users to manage their data locally and without mandatory cloud storage. This combination ensures that information does not exist in isolation but in a network of links, thereby enabling it to be viewed and utilized in different contexts and from various perspectives – or in Anytype terminology, “Views”. The ability to structure data through “Sets” and “Relations” allows users to develop complex semantic structures that maximize the value of the connected information.

In terms of knowledge management, Anytype provides a platform that not only enables the organization of information but also its linkage and rediscovery in an intuitive and user-friendly format. The ability to create one’s own object types and relationships between them promotes clear organization and intuitive navigation, especially in information-dense and complex projects. Here, the value of information is particularly emphasized when it is related to others, thus forming a network of knowledge and data that can be made visible from various “Views”.

The PARA concept, which divides information into the categories of Projects, Areas, Resources, and Archives, provides a structuring level that organizes processes and knowledge in a clear and comprehensible manner. This structuring can be effectively represented in Anytype, especially through the use of Sets, Tags, Relations, and status displays, to create a clear and navigable knowledge database. This approach to implementing PARA in Anytype, with particular emphasis on linking and visualizing information, will be detailed in the course of this article.

For a detailed explanation, check my article: https://haak3.de/articles/2023_Anytype/2023_Anytype-mit-PARA/2023_Using-PARA-with-Anytype-EN.html

### Categories

Work, Project tracking

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by fuksman** [comment]
@ChristianHaake please edit this and other experiences from today: screenshot should be png, not jpeg.
P.S. Great submission, btw!

**Comment by ChristianHaake** [comment]
done. Are gifs ok?

**Comment by fuksman** [comment]
Everything is build for png, but will try to include a gif manually. Thanks!

**Comment by fuksman** [comment]
Saving gif for later:
![2023-10-14_Anytype-PARA-Source-gif](https://github.com/anyproto/gallery/assets/48489823/4158583f-941c-4de0-90f7-e81d9f8f58d9)
