### ISSUE TITLE
Habit Tracker

### ISSUE THREAD

**Issue by darshansharma** [anyproto/gallery#39]
### Experience

My Routine Set consisted of 3 or 4 must-do habits that I must do every day. The Responses of these are either Yes or No.
The purpose is to instill a daily routine of must-do habits and then after 1 month, you can see how the graph is going. 
As they say, repeated habit is the sole determination of the character of a person. 

| Task 1   |  Task 2 | Task 3  | Task 4  |   |
|---|---|---|---|---|
| Y  | Y  | Y  | Y  |   |
|  Y |  Y | Y  |  Y |   |
|  Y |  Y | Y  | Y  |   |

[Habit.Tracker.zip](https://github.com/anyproto/gallery/files/14083842/Habit.Tracker.zip)

### Title

Routine Set Ticker

### Screenshots

<img width="838" alt="Screenshot 2024-01-29 at 12 06 56 AM" src="https://github.com/anyproto/gallery/assets/14093291/7aa45681-ed21-42c4-9103-914e8ac2e46c">

<img width="1148" alt="Screenshot 2024-01-29 at 12 41 36 AM" src="https://github.com/anyproto/gallery/assets/14093291/6c1a418b-f12c-4958-8a22-a0b9fcea39e2">

### Description

Crossing off daily habits, routines, or tasks provides that much-needed "shot in the arm" of dopamine, propelling you forward. It ensures that you "keep the ball rolling," even when the temptation to stop is strong, thus cultivating a "can-do" attitude. 

### Categories

Personal Growth

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by jmetrikat** [comment]
hey @darshansharma, please add the link to the zip file under the Experience field, in order for the submission to be checked again. it should look like this:

```
### Experience

[Habit.Tracker.zip](https://github.com/anyproto/gallery/files/14083669/Habit.Tracker.zip)

```

thanks!
