### ISSUE TITLE
Story Forge Project Manager

### ISSUE THREAD

**Issue by axisnova** [anyproto/gallery#51]
### Experience

A place to write and develop a fictional story and develop a more living and breathing fleshed out story.
Build and connect different elements of your story to help refine details or recall them at a later point or for use in a different story.
Templates for each area give you a good starting place to generate more ideas.

Version 1
[SFPM.zip](https://github.com/anyproto/gallery/files/14759191/SFPM.zip)

### Title

Story Forge Project Manager

### Screenshots

![Anytype_wHUVffWrjV](https://github.com/anyproto/gallery/assets/591056/9ebed95e-781d-4265-984e-aef7c3f0e659)
![Anytype_3D89lMdOFB](https://github.com/anyproto/gallery/assets/591056/4c026d51-f2ae-4c1b-b777-ceb96c087222)
![Anytype_q6Q0xrkb7t](https://github.com/anyproto/gallery/assets/591056/ef3b0a8d-dd51-4747-b2c2-6d313dc5db8c)

### Description

A place to write and develop a fictional story and develop a more living and breathing fleshed out story.
Version 1
### Categories

Dashboard, Project tracking, Hobbies, Other

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by KirillSto** [comment]
@axisnova it seems that majority of relations have not been added to exported archive. Especially those that are presented in relation blocks of template objects:
![image](https://github.com/anyproto/gallery/assets/40611691/c975ba1a-f7cc-476a-98ee-b6e696d37257)
Are you sure you made export of whole space, not the export of bunch of objects?

BTW we are going to improve our exporting process in case of choise of limited set, but right now the best way to deliver experience is to make export of space.

If your former space is still available, can you please do export one more time :pray:  You can share resulting archive in the comment, or substitute it in issue description yourself

**Comment by axisnova** [comment]
Sure, I'll get you another copy I pulled that one back in as a space and it worked but I saw some other glaring issues I'm trying to fix too. Could it be that I was on a nightly build that it didn't pull in for you correctly?

**Comment by KirillSto** [comment]
> Sure, I'll get you another copy I pulled that one back in as a space and it worked but I saw some other glaring issues I'm trying to fix too. Could it be that I was on a nightly build that it didn't pull in for you correctly?

Thank you, waiting for updated archive than! :relieved: 

Latest nightly builds share stable exporting process, so I think it's more likely connected with other export method chosen. For now we recommend to use Export Space to make fully linked experiences:
![image](https://github.com/anyproto/gallery/assets/40611691/6d9dab69-fd82-4c27-9b17-6482d856c705)

**Comment by axisnova** [comment]
[Anytype.20240304.020425.66.zip](https://github.com/anyproto/gallery/files/14477705/Anytype.20240304.020425.66.zip)
Yeah, that's how I did it the first time. I have imported it back into a new space to test things and have run into quite a few issues, I have been trying to go through them to see which ones might just be me doing something.

I'll post these in the nightly slack as well. But the big ones I've run into are 
The views in the set are not remembering which object type they are pointed at. 
It's pretty much broke the whole storylines template not remembering any of the views or filters I set up or even the set itself. I didn't have this problem generating the template over and over again originally just in the version has been exported and imported again so it must be getting lost along the way.
The way I have the sets made it also pulls the actual template for each view I can't filter for that because the object type 'Template" is not available. In addition to this, some of them pull the template more than once even though I only created one template.

Does this version populate the relations? I hope haha

**Comment by KirillSto** [comment]
Yeah, thank you, @axisnova !
Now all relation objects are presented in the archive, so just a bunch of corrections should be made to restore some links between objects. It seems that some type ids were missing while exporting, we saw that bug before in sets and templates.
I will fix it throughout the day :wink:

**Comment by axisnova** [comment]
https://github.com/anyproto/gallery/assets/591056/893cc996-ed14-46a6-8c0a-bbd100f90224

Just to show what's happening between the export and the import. Already if it was working and remembering that set without erasing the views. Since there is no way to set a global filter across the views anyone using it would have to change the filters to point at the proper storyline each time they made a new one.
