### ISSUE TITLE
Zen System

### ISSUE THREAD

**Issue by Hexara7777** [anyproto/gallery#53]
### Experience

[zen.zip](https://github.com/anyproto/gallery/files/14459962/zen.zip)

### Title

Zen System

### Screenshots

![1](https://github.com/anyproto/gallery/assets/130001839/2e1958fe-60fb-45ac-964a-6ae537a2a007)

### Description

Easy to use system that partially follows the PARA methodology.
More details: https://community.anytype.io/t/zen-system-v0-2-added-to-experience-gallery/12791

### Categories

Dashboard, Personal Growth, Project tracking

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by Hexara7777** [comment]
I don't understand what the problem is.

**Comment by KirillSto** [comment]
@Hexara7777 everything is ok! 
I was just testing our automatic validator, your experience is approved

**Comment by KirillSto** [comment]
> But it didn't get updated on the gallery D: Still the old images and description.

You can check it now please. The experience should be update it in the very repo. A little bit later we will update our index, so your experience will be updated in our site and gallery tab as well
