### ISSUE TITLE
Plant Tracker

### ISSUE THREAD

**Issue by p1xelll** [anyproto/gallery#62]
### Experience

[Plant.Tracker.zip](https://github.com/anyproto/gallery/files/14736802/Plant.Tracker.zip)

### Title

Plant Tracker

### Screenshots

![Screenshot 1](https://github.com/anyproto/gallery/assets/81173399/4971c83f-ce03-4b1c-9114-3faad9943bc4)
<img width="1840" alt="Screenshot 2" src="https://github.com/anyproto/gallery/assets/81173399/849bf084-a635-47a2-b352-655d8f16e20e">

### Description

Plant Tracker is your digital plant oasis. Keep your houseplant jungle organised with details like watering schedules, light requirements and happy snaps to track their growth.

### Categories

Hobbies

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by fuksman** [comment]
Hey @p1xelll, we will fix this ourselves 🪴
