### ISSUE TITLE
Adventure Hub

### ISSUE THREAD

**Issue by Adventure-nerd** [anyproto/gallery#73]
### Experience
[Anytype.20240401.161407.59.zip](https://github.com/anyproto/gallery/files/14829391/Anytype.20240401.161407.59.zip)

### Title

Adventure Hub

### Screenshots

<img width="593" alt="Adventure Hub 6" src="https://github.com/anyproto/gallery/assets/164412107/079d745f-316f-48a7-a884-2fe1163a1f7d">
<img width="515" alt="Adventure Hub 5" src="https://github.com/anyproto/gallery/assets/164412107/9ec7cfa6-2a06-4c2b-bf72-3993933f1bd8">
<img width="683" alt="Adventure Hub 4" src="https://github.com/anyproto/gallery/assets/164412107/6faa7307-e73b-4f13-a1c1-bf38f2704376">
<img width="584" alt="Adventure Hub 3" src="https://github.com/anyproto/gallery/assets/164412107/01483adf-d64d-4f11-af84-4246bcbe8423">
<img width="488" alt="Adventure Hub 2" src="https://github.com/anyproto/gallery/assets/164412107/e37ac48c-0fc5-4d81-9963-3c775b41c37b">
<img width="553" alt="Adventure Hub 1" src="https://github.com/anyproto/gallery/assets/164412107/f21e6f65-8a99-4074-8cbb-81d0d254ec58">

### Description

Here you can track your adventure plans or "bucket list" adventures. I have included a few adventure types to include as many to make it easier. Anything that is irrelevant to you , you can delete the Type in the library, and the corresponding set. 

### Categories

Hobbies

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by fuksman** [comment]
Hello @Adventure-nerd, did you close your submission intentionally?
