### ISSUE TITLE
Adventure Hub

### ISSUE THREAD

**Issue by Adventure-nerd** [anyproto/gallery#74]
### Experience

[Adventure_Hub.zip](https://github.com/anyproto/gallery/files/14890604/Adventure_Hub.zip)

### Title

Adventure Hub

### Screenshots

<img width="593" alt="Adventure Hub 6" src="https://github.com/anyproto/gallery/assets/164412107/14d89506-8dcd-4f28-ad22-2cb8321a3126">
<img width="515" alt="Adventure Hub 5" src="https://github.com/anyproto/gallery/assets/164412107/ed8fcd14-1235-477a-96d1-a0fb31e0df0d">
<img width="683" alt="Adventure Hub 4" src="https://github.com/anyproto/gallery/assets/164412107/462273c2-2f26-4de1-932d-e28492d3c945">
<img width="584" alt="Adventure Hub 3" src="https://github.com/anyproto/gallery/assets/164412107/85f936d5-d6f6-47c1-b26e-0f6165a3d6b0">
<img width="488" alt="Adventure Hub 2" src="https://github.com/anyproto/gallery/assets/164412107/5bf90cb9-067f-4106-94b1-1b04b4717c23">
<img width="553" alt="Adventure Hub 1" src="https://github.com/anyproto/gallery/assets/164412107/48d29b92-289a-40ac-bad4-8e9484918f22">

### Description

Here you can track your adventure plans or "bucket list" adventures. I have included several Adventure Types to make it easier. Anything that is irrelevant to you , you can delete the Type in the library, and the corresponding set.

### Categories

Hobbies

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by fuksman** [comment]
Hey @Adventure-nerd, we will fix this ourselves. Thank you for the submission!

**Comment by Adventure-nerd** [comment]
Thanks I appreciate it! I'm happy to contribute 😁 as I continue to
contribute, how will this link up with my karma? I'm not entirely sure how
my GitHub account will link with everything, other than a common email.
Thanks!
