### ISSUE TITLE
AnyType for Content Creators

### ISSUE THREAD

**Issue by AlderpenGhub** [anyproto/gallery#84]
### Experience

[Anytype4ContentCreators.zip](https://github.com/anyproto/gallery/files/14922672/Anytype4ContentCreators.zip)

### Title

AnyType for Content Creators

### Screenshots

![AnyType Template 001](https://github.com/anyproto/gallery/assets/17861962/181b4d45-5654-4e40-a8f2-7577984549f3)
![AnyType Template 006](https://github.com/anyproto/gallery/assets/17861962/6e1e44c3-78b4-48d6-a02e-027b76c1a0fd)
![AnyType Template 002](https://github.com/anyproto/gallery/assets/17861962/540d1dc9-b8d7-4c16-8b10-56420114babc)
![AnyType Template 003](https://github.com/anyproto/gallery/assets/17861962/dc74931b-135a-4128-8c6a-73b39bcf94e5)
![AnyType Template 004](https://github.com/anyproto/gallery/assets/17861962/ecc50a36-b9c5-4c0a-9d53-291f4196e2c5)
![AnyType Template 005](https://github.com/anyproto/gallery/assets/17861962/87cc16bd-d374-4fbe-b5ea-abd0d4809a9b)

### Description

This template is a simple tool to allow new Content Creators to have a way to manage and track their video production workflow. With an intuitive menu on the left and author notes with video tutorials that will be coming in April of 2024.

### Categories

Dashboard, Work, Project tracking, Other

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by AlderpenGhub** [comment]
[Anytype.20240407.031415.49.zip](https://github.com/anyproto/gallery/files/14896082/Anytype.20240407.031415.49.zip)

**Comment by AlderpenGhub** [comment]
I think this fixed the issue?

**Comment by KirillSto** [comment]
Thank you for your contribution, @AlderpenGhub !
A new version of experience validator is coming, so we will fix the archive automatically!
