### ISSUE TITLE
RPG Repository

### ISSUE THREAD

**Issue by 7ede** [anyproto/gallery#85]
### Experience

[RPG_Repo_7ede.zip](https://github.com/user-attachments/files/15570723/RPG_Repo_7ede.zip)

### Title

RPG Repository

### Screenshots

![Schermata del 2024-04-07 20-20-51](https://github.com/anyproto/gallery/assets/42887870/1130f33b-907a-4d3b-bf62-04e4f5ceddf9)
![Schermata del 2024-04-07 20-20-59](https://github.com/anyproto/gallery/assets/42887870/dec4ed41-c6b4-4863-a08d-2f18ab269e48)
![Schermata del 2024-04-07 20-21-12](https://github.com/anyproto/gallery/assets/42887870/d9f2ac68-2fbc-4f07-b5a6-23482a9c9c3b)
![Schermata del 2024-04-07 20-21-20](https://github.com/anyproto/gallery/assets/42887870/220b27a1-eef2-43eb-ac79-0b9360c530f6)
![Schermata del 2024-04-07 20-21-29](https://github.com/anyproto/gallery/assets/42887870/e8c5542c-4a7b-47c5-92b2-513a580a6a59)
![Schermata del 2024-04-07 20-21-46](https://github.com/anyproto/gallery/assets/42887870/4f6368ce-6170-474b-9ef4-78cde3962ff4)
![Schermata del 2024-04-07 20-21-52](https://github.com/anyproto/gallery/assets/42887870/2dfef8d5-7717-415d-aee6-76f087f9c4a4)
![Schermata del 2024-04-07 20-21-56](https://github.com/anyproto/gallery/assets/42887870/109a0355-3c6c-4a9d-aad2-03a5fbef2793)
![Schermata del 2024-04-07 20-22-03](https://github.com/anyproto/gallery/assets/42887870/67cae738-c0ae-4e06-b278-3045bdfd6a19)
![Schermata del 2024-04-07 20-22-59](https://github.com/anyproto/gallery/assets/42887870/f36b0e98-65d1-49c5-ad57-de564f7198c4)
![Schermata del 2024-04-07 20-23-17](https://github.com/anyproto/gallery/assets/42887870/0822e54e-5790-4a4c-b78f-14eec8f6a139)
![Schermata del 2024-04-07 20-22-23](https://github.com/anyproto/gallery/assets/42887870/bc869d91-32c9-4fdd-9eb8-aa3fd22d9f8c)

### Description

Dear DMs, this Experience will allow you to manage the Campaigns of your favorite RPGs with a series of elements designed to archive information with order and precision. The whole thing is adaptable to different rulesets with ease. Demo campaign included!

### Categories

Hobbies

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by 7ede** [comment]
Don’t know what to do 🤷🏻‍♂️ I’m not a programmer, could someone explain me what the “validator output” means?

**Comment by KirillSto** [comment]
Thank you for your contribution, @7ede !
Don't worry! The new version of validator is coming, so the archive will be processed automatically :hugs:

**Comment by 7ede** [comment]
> Thank you for your contribution, @7ede ! Don't worry! The new version of validator is coming, so the archive will be processed automatically 🤗

Hi, is there any news? Are my contribution going to be approved?

**Comment by fuksman** [comment]
Hello @7ede, of course it will be approved, and I am terribly sorry for the delay: we're under the pressure of tasks after multiplayer & membership release. Will address this asap.
