### ISSUE TITLE
Items Lent out / Borrowed Tracker

### ISSUE THREAD

**Issue by nima9** [anyproto/gallery#90]
### Experience

[ILOBT.zip](https://github.com/user-attachments/files/15570136/ILOBT.zip)

This is the exported space for "Items Lent out/Borrowed Tracker"

### Title

Items Lent out/Borrowed Tracker

### Screenshots

<img width="2155" alt="1" src="https://github.com/anyproto/gallery/assets/26048890/08331a7d-3957-4592-90ea-b7ac91ad36b9">
<img width="2547" alt="2" src="https://github.com/anyproto/gallery/assets/26048890/86defb55-6f58-4e9e-b048-24eb844cc214">
<img width="1563" alt="3" src="https://github.com/anyproto/gallery/assets/26048890/2b3edb2d-7fa6-4064-959a-4945981c0595">
<img width="1456" alt="4" src="https://github.com/anyproto/gallery/assets/26048890/3ca23e5b-a506-4a4a-9ebe-550481b27418">

### Description

This is really useful for keeping tracking of things that I have borrowed or things I have lent out to others.

### Categories

Home

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by fuksman** [comment]
Hey @nima9, can you please re-upload screenshot in .png?

**Comment by nima9** [comment]
Done

**Comment by fuksman** [comment]
Thanks, we will fix the validation issues on our side
